#!/bin/bash
  
domains=("acquire" "connect" "cover" "enable")

for i in "${domains[@]}"
do
 LINES=$(cat $i-domain)

for LINE in $LINES
do
    aws resourcegroupstaggingapi get-resources --resource-type-filters rds:db --tag-filters  Key=everquote:domain --output json | jq -r '.ResourceTagMappingList[].Tags[] | select(.Key=="everquote:domain").Value' > alldomains.txt
    #echo $i:"$LINE" >> testfile.txt
done
done

cat testfile.txt | wc -l 
rm testfile.txt
