name: Test Suite

on:
  push:
    branches:
      - master
    paths:
      - 'deploy/**'

jobs:
  set_up:
    runs-on: ubuntu-latest
    name: Basic Usage Test
    permissions:
      id-token: write
      contents: read
    outputs:
      staging: ${{ steps.filter.outputs.staging }}
      prod: ${{ steps.filter.outputs.prod }}
      matrix-prod: ${{ steps.set-matrix.outputs.matrix-prod }}
      matrix-staging: ${{ steps.set-matrix.outputs.matrix-staging }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  
          
      - name: filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            staging:
              - 'deploy/*staging/**'
            prod:
              - 'deploy/*prod/**'

      - name: List all changed files
        if: steps.filter.outputs.staging == 'true' || steps.filter.outputs.prod == 'true'
        run: |
         staging_applications=(${{ steps.filter.outputs.staging_files }})
         IFS=','
         filtered_staging_apps=()
         filtered_staging_clusters=()
         filtered_prod_apps=()
         filtered_prod_clusters=()
         
         # Get the staging application names first
         for staging_file in ${staging_applications[@]}; do
            staging_base="$(dirname $staging_file)"
            staging_application="$(basename $staging_base)"
            filtered_staging_apps+=("$staging_application") 
         # Get the staging cluster names 
         if [[ $staging_file == *base-config*]];
         then
            staging_cluster_name=$(dirname $staging_file)
            filtered_staging_clusters+=("$staging_cluster_name")
         else
            staging_filter_1=$(dirname $staging_file)
            staging_filter_2=$(dirname $staging_filter_1)
            staging_cluster_name=$(basename $staging_filter_2)
            filtered_staging_clusters+=("$staging_cluster_name")
         done
         echo "applications_staging=${filtered_staging_apps[@]}" >> $GITHUB_ENV
         echo ${filtered_staging_clusters[@]} |  tr -d '\n' | jq -R -s -c 'split(" ")'
         
         prod_applications=(${{ steps.filter.outputs.prod_files }})
         IFS=','
         for prod_file in ${prod_applications[@]}; do
            prod_base="$(dirname $prod_file)"
            prod_application="$(basename $prod_base)"
            filtered_prod_apps+=("$prod_application")  
         done
         echo "applications_prod=${filtered_prod_apps[@]}" >> $GITHUB_ENV
         
      - name: set-matrix 
        id: set-matrix
        if: steps.filter.outputs.staging == 'true' || steps.filter.outputs.prod == 'true'
        run: | 
         echo "${{ env.applications_staging }}"
         echo "::set-output name=matrix-staging::$(echo ${{ env.applications_staging }} | tr -d '\n' | jq -R -s -c 'split(" ")')"
         echo "${{ env.applications_prod }}"
         echo "::set-output name=matrix-prod::$(echo ${{ env.applications_prod }} | tr -d '\n' | jq -R -s -c 'split(" ")')"
           
  prod_dts: 
    needs: set_up
    if: ${{ needs.set_up.outputs.prod == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix: 
       value: ${{ fromJson(needs.set_up.outputs.matrix-prod) }}
    steps:
    - run: echo ${{ matrix.value }}

  staging_dts: 
    needs: set_up
    if: ${{ needs.set_up.outputs.staging == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix: 
       value: ${{ fromJson(needs.set_up.outputs.matrix-staging) }}
    steps:
    - run: echo ${{ matrix.value }}

 # env_name=()
  #prod_applications_1=()
  for file in $prod_applications; do
# Get the application name first
     base=$(dirname $file)
     application=$(basename $base)
     prod_applications_1+=("$application")
# Now get the cluster name 
  if [[ $file == *base-config* ]]; 
  then
     base2=$(dirname $base)
     env_name+=("$base2")
  else
     base2=$(dirname $base)
     base3=$(dirname $base2 )
     base4=$(basename $base3)
     env_name+=("$base4")
  fi  
  done
echo ${prod_applications_1[@]} |  tr -d '\n' | jq -R -s -c 'split(" ")' 
echo ${env_name[@]} |  tr -d '\n' | jq -R -s -c 'split(" ")' 
