name: Test Suite

on:
  push:
    branches:
      - master
    paths:
      - 'deploy/**'

jobs:
  basic_test:
    runs-on: ubuntu-latest
    name: Basic Usage Test
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  
          
      - name: filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            prod:
              - 'deploy/*prod/**'
            staging:
              - 'deploy/*staging/**'
                      
      - name: List all changed prod files
        if: steps.filter.outputs.prod == 'true'
        run: |
         echo ${{ steps.filter.outputs.prod_files }} > rawfiles.yml
         cat rawfiles.yml
         prod_applications=()
         for file in ${{ steps.filter.outputs.prod_files }}; do
            echo "$file was changed"
            base="$(dirname $file)"
            application="$(basename $base)"
            prod_applications+=("$application")
         done
         echo ${prod_applications[@]}
         
      - name: List all changed staging files
        if: steps.filter.outputs.staging == 'true'
        run: |
         echo ${{ steps.filter.outputs.staging_files }}
         for file in ${{ steps.filter.outputs.staging_files }}; do
            echo "$file was changed"
            base="$(dirname $file)"
            application="$(basename $base)"
         done
         echo $application
              
  #    - name: Prod DTS trigger
     #   if: steps.filter.outputs.prod == 'true'
      #  uses: dorny/paths-filter@v2
      #  run: echo ${{ steps.filter.outputs.prod_files }}
                 
      

     # - name: Test deployment tracker
      #  uses: everquoteinc/deployment-tracker-action@v1
       # with:
        #  application-name: deployment-tracker-action
         # platform: "developer experience"
         # environment: unspec
         # deployment-status: start
        #  aws-region: us-east-1
          
          
