name: Test Suite

on:
  #pull_request:
  push:
    branches:
      - master
    paths:
      - 'gha-dts/**'

jobs:
  basic_test:
    runs-on: ubuntu-latest
    name: Basic Usage Test
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
          
      - name: filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            path1:
              - 'prod/**'
              
           # run only if 'backend' files were changed
      - name: backend tests
        if: steps.filter.outputs.path1 == 'true'
        run: echo prod has been changed
     
   #   - name: Run changed-files with defaults on the dir1
    #    id: changed-files-for-dir1
    #    uses: tj-actions/changed-files@v21
    #    with:
     #     path: gha-dts
                 
    #  - name: List all changed files
      #  run: |
       #   for file in ${{ steps.changed-files-for-dir1.outputs.added_files }}; do
        #    echo "$file was changed"
       #   done

     # - name: Test deployment tracker
      #  uses: everquoteinc/deployment-tracker-action@v1
       # with:
        #  application-name: deployment-tracker-action
         # platform: "developer experience"
         # environment: unspec
         # deployment-status: start
        #  aws-region: us-east-1
          
          
