name: Test Suite

on:
  #pull_request:
  push:
    branches:
      - master
    paths:
      - 'gha-dts/**'

jobs:
  basic_test:
    runs-on: ubuntu-latest
    name: Basic Usage Test
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  
          
      - name: filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            prod:
              - 'gha-dts/*prod/**'
              
  #    - name: Prod DTS trigger
     #   if: steps.filter.outputs.prod == 'true'
      #  uses: dorny/paths-filter@v2
      #  run: echo ${{ steps.filter.outputs.prod_files }}
                 
      - name: List all changed files
        if: ${{ steps.filter.outputs.prod == 'true' }}
        run: |
         for file in ${{ steps.filter.outputs.prod_files }}; do
            echo "$file was changed"
         done

     # - name: Test deployment tracker
      #  uses: everquoteinc/deployment-tracker-action@v1
       # with:
        #  application-name: deployment-tracker-action
         # platform: "developer experience"
         # environment: unspec
         # deployment-status: start
        #  aws-region: us-east-1
          
          
