name: Test Suite

on:
  push:
    branches:
      - master
    paths:
      - 'deploy/**'

jobs:
  set_up:
    runs-on: ubuntu-latest
    name: Basic Usage Test
    permissions:
      id-token: write
      contents: read
    outputs:
      all_files: ${{ steps.filter.outputs.all_files }}
      matrix_files: ${{ steps.set-matrix.outputs.matrix_files }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  
          
      - name: filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            all_files:
              - 'deploy/**/**'

      - name: List all changed files
        if: steps.filter.outputs.all_files == 'true'
        run: |
         all_applications=(${{ steps.filter.outputs.all_files_files }})
         IFS=','
         filtered_apps=()
         
         # Get the application names first
         for file in ${all_applications[@]}; do
            filtered_apps+=("$file") 
         done
         echo "filtered_applications=${filtered_apps[@]}" >> $GITHUB_ENV         
         
      - name: set-matrix 
        id: set-matrix
        if: steps.filter.outputs.all_files == 'true'
        run: | 
         echo "::set-output name=matrix_files::$(echo ${{ env.filtered_applications }} | tr -d '[]' | tr -d '\n' | jq -R -s -c 'split(" ")')"         
         
  prod_dts: 
    needs: set_up
    if: ${{ needs.set_up.outputs.all_files == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix: 
       app-value: ${{ fromJson(needs.set_up.outputs.matrix_files) }}
    steps:
    - name: get the name and cluster name
      run: |
          test=${{ matrix.app-value }}
          cluster=$(awk -F/ '{print $2}' <<< "$test")
          application=$(awk -F/ '{print $(NF-1)}' <<< "$test")
          environment=$(awk -F- '{print $NF}' <<< "$cluster")
          
          echo cluster is: $cluster
          echo application is: $application
          echo environment is: $environment

        
       # echo "prod_application_name=$base1" >> $GITHUB_ENV
       # echo "prod_cluster_name=$base4" >> $GITHUB_ENV

  #  - name: test print prod variables 
      #run: |
       # echo "${{ env.prod_application_name }}" 
       # echo "${{ env.prod_cluster_name }}" 

