name: Test Suite

on:
  push:
    branches:
      - master
    paths:
      - 'deploy/**'

jobs:
  basic_test:
    runs-on: ubuntu-latest
    name: Basic Usage Test
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  
          
      - name: filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            staging:
              - 'deploy/*staging/**'
            prod:
              - 'deploy/*prod/**'
              
      - name: List all changed staging files
        if: steps.filter.outputs.staging == 'true'
        run: |
         staging_applications=(${{ steps.filter.outputs.staging_files }})
         IFS=','
         filtered_staging_apps=()
         for staging_file in ${staging_applications[@]}; do
            staging_base="$(dirname $staging_file)"
            staging_application="$(basename $staging_base)"
            filtered_staging_apps+=("$staging_application") 
         done
         echo "applications_staging=${filtered_staging_apps[@]}" >> $GITHUB_ENV
        # for staging_value in "${filtered_staging_apps[@]}"; do
         #   echo $staging_value
         #done
                      
      - name: List all changed prod files
        if: steps.filter.outputs.prod == 'true'
        run: |
         prod_applications=(${{ steps.filter.outputs.prod_files }})
         IFS=','
         filtered_prod_apps=()
         for prod_file in ${prod_applications[@]}; do
            prod_base="$(dirname $prod_file)"
            prod_application="$(basename $prod_base)"
            filtered_prod_apps+=("$prod_application")  
         done
         echo "applications_prod=${filtered_prod_apps[@]}" >> $GITHUB_ENV
        # for prod_value in "${filtered_prod_apps[@]}"; do
         #   echo $prod_value
        # done
         
      - name: test-env-variable-staging
        if: steps.filter.outputs.staging == 'true'
        run: | 
         echo "${{ env.applications_staging }}"
         
      - name: test-env-variable-prod
        if: steps.filter.outputs.prod == 'true'
        run: | 
         echo "${{ env.applications_prod }}"
              
  #    - name: Prod DTS trigger
     #   if: steps.filter.outputs.prod == 'true'
      #  uses: dorny/paths-filter@v2
      #  run: echo ${{ steps.filter.outputs.prod_files }}
                 
      

     # - name: Test deployment tracker
      #  uses: everquoteinc/deployment-tracker-action@v1
       # with:
        #  application-name: deployment-tracker-action
         # platform: "developer experience"
         # environment: unspec
         # deployment-status: start
        #  aws-region: us-east-1
          
          
