name: Test Suite

on:
  push:
    branches:
      - master
    paths:
      - 'deploy/**'

jobs:
  set_up:
    runs-on: ubuntu-latest
    name: Basic Usage Test
    permissions:
      id-token: write
      contents: read
    outputs:
      matrix-prod: ${{ steps.set-matrix-prod.outputs.matrix-prod }}
      matrix-staging: ${{ steps.set-matrix-staging.outputs.matrix-staging }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  
          
      - name: filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            staging:
              - 'deploy/*staging/**'
            prod:
              - 'deploy/*prod/**'
              
      - name: List all changed staging files
        if: steps.filter.outputs.staging == 'true'
        run: |
         staging_applications=(${{ steps.filter.outputs.staging_files }})
         IFS=','
         filtered_staging_apps=()
         for staging_file in ${staging_applications[@]}; do
            staging_base="$(dirname $staging_file)"
            staging_application="$(basename $staging_base)"
            filtered_staging_apps+=("$staging_application") 
         done
         echo "applications_staging=${filtered_staging_apps[@]}" >> $GITHUB_ENV
                      
      - name: List all changed prod files
        if: steps.filter.outputs.prod == 'true'
        run: |
         prod_applications=(${{ steps.filter.outputs.prod_files }})
         IFS=','
         filtered_prod_apps=()
         for prod_file in ${prod_applications[@]}; do
            prod_base="$(dirname $prod_file)"
            prod_application="$(basename $prod_base)"
            filtered_prod_apps+=("$prod_application")  
         done
         echo "applications_prod=${filtered_prod_apps[@]}" >> $GITHUB_ENV
        # for prod_value in "${filtered_prod_apps[@]}"; do
         #   echo $prod_value
        # done
         
      - name: deploy-staging
        id: set-matrix-staging
        if: steps.filter.outputs.staging == 'true'
        run: | 
         echo "${{ env.applications_staging }}"
         echo "::set-output name=matrix-staging::$(echo ${{ env.applications_staging }} | tr -d '\n' | jq -R -s -c 'split(" ")')"

         
      - name: deploy-prod
        id: set-matrix-prod
        if: steps.filter.outputs.prod == 'true'
        run: | 
         echo "${{ env.applications_prod }}"
         echo "::set-output name=matrix-prod::$(echo ${{ env.applications_prod }} | tr -d '\n' | jq -R -s -c 'split(" ")')"
         
  prod_dts: 
    needs: set_up
    runs-on: ubuntu-latest
    strategy:
      matrix: 
       value: ${{ fromJson(needs.set_up.outputs.matrix-prod) }}
    steps:
    - run: echo ${{ matrix.value }}
    
  staging_dts: 
    needs: set_up
    runs-on: ubuntu-latest
    strategy:
      matrix: 
       value: ${{ fromJson(needs.set_up.outputs.matrix-staging) }}
    steps:
    - run: echo ${{ matrix.value }}


                 
      

     # - name: Test deployment tracker
      #  uses: everquoteinc/deployment-tracker-action@v1
       # with:
        #  application-name: deployment-tracker-action
         # platform: "developer experience"
         # environment: unspec
         # deployment-status: start
        #  aws-region: us-east-1
          
          
